apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: holdwall

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - service-accounts.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml
  - app-pdb.yaml
  - worker-deployment.yaml
  - outbox-worker-deployment.yaml
  - cronjobs.yaml
  - ingress.yaml
  - network-policy.yaml

commonLabels:
  app: holdwall
  managed-by: kustomize
